/** BCC suburb-boundaries open data, fetched 2026-08-25. Mainland localities only.
 *  Source: https://data.brisbane.qld.gov.au/explore/dataset/suburb-boundaries/
 *  Moreton Island localities omitted — no kerbside purple-bin run.
 */
export type BrisbaneSuburb = {
  slug: string;
  name: string;
  wedge: boolean;
};

export const BRISBANE_SUBURBS: BrisbaneSuburb[] = [
  { slug: "annerley", name: "Annerley", wedge: true },
  { slug: "coorparoo", name: "Coorparoo", wedge: true },
  { slug: "dutton-park", name: "Dutton Park", wedge: true },
  { slug: "fairfield", name: "Fairfield", wedge: true },
  { slug: "greenslopes", name: "Greenslopes", wedge: true },
  { slug: "highgate-hill", name: "Highgate Hill", wedge: true },
  { slug: "moorooka", name: "Moorooka", wedge: true },
  { slug: "rocklea", name: "Rocklea", wedge: true },
  { slug: "salisbury", name: "Salisbury", wedge: true },
  { slug: "south-brisbane", name: "South Brisbane", wedge: true },
  { slug: "tarragindi", name: "Tarragindi", wedge: true },
  { slug: "tennyson", name: "Tennyson", wedge: true },
  { slug: "west-end", name: "West End", wedge: true },
  { slug: "woolloongabba", name: "Woolloongabba", wedge: true },
  { slug: "yeerongpilly", name: "Yeerongpilly", wedge: true },
  { slug: "yeronga", name: "Yeronga", wedge: true },
  { slug: "acacia-ridge", name: "Acacia Ridge", wedge: false },
  { slug: "albion", name: "Albion", wedge: false },
  { slug: "alderley", name: "Alderley", wedge: false },
  { slug: "algester", name: "Algester", wedge: false },
  { slug: "anstead", name: "Anstead", wedge: false },
  { slug: "archerfield", name: "Archerfield", wedge: false },
  { slug: "ascot", name: "Ascot", wedge: false },
  { slug: "ashgrove", name: "Ashgrove", wedge: false },
  { slug: "aspley", name: "Aspley", wedge: false },
  { slug: "auchenflower", name: "Auchenflower", wedge: false },
  { slug: "bald-hills", name: "Bald Hills", wedge: false },
  { slug: "balmoral", name: "Balmoral", wedge: false },
  { slug: "banks-creek", name: "Banks Creek", wedge: false },
  { slug: "banyo", name: "Banyo", wedge: false },
  { slug: "bardon", name: "Bardon", wedge: false },
  { slug: "bellbowrie", name: "Bellbowrie", wedge: false },
  { slug: "belmont", name: "Belmont", wedge: false },
  { slug: "boondall", name: "Boondall", wedge: false },
  { slug: "bowen-hills", name: "Bowen Hills", wedge: false },
  { slug: "bracken-ridge", name: "Bracken Ridge", wedge: false },
  { slug: "bridgeman-downs", name: "Bridgeman Downs", wedge: false },
  { slug: "brighton", name: "Brighton", wedge: false },
  { slug: "brisbane-airport", name: "Brisbane Airport", wedge: false },
  { slug: "brisbane-city", name: "Brisbane City", wedge: false },
  { slug: "brookfield", name: "Brookfield", wedge: false },
  { slug: "bulimba", name: "Bulimba", wedge: false },
  { slug: "burbank", name: "Burbank", wedge: false },
  { slug: "calamvale", name: "Calamvale", wedge: false },
  { slug: "camp-hill", name: "Camp Hill", wedge: false },
  { slug: "cannon-hill", name: "Cannon Hill", wedge: false },
  { slug: "carina", name: "Carina", wedge: false },
  { slug: "carina-heights", name: "Carina Heights", wedge: false },
  { slug: "carindale", name: "Carindale", wedge: false },
  { slug: "carseldine", name: "Carseldine", wedge: false },
  { slug: "chandler", name: "Chandler", wedge: false },
  { slug: "chapel-hill", name: "Chapel Hill", wedge: false },
  { slug: "chelmer", name: "Chelmer", wedge: false },
  { slug: "chermside", name: "Chermside", wedge: false },
  { slug: "chermside-west", name: "Chermside West", wedge: false },
  { slug: "chuwar", name: "Chuwar", wedge: false },
  { slug: "clayfield", name: "Clayfield", wedge: false },
  { slug: "coopers-plains", name: "Coopers Plains", wedge: false },
  { slug: "corinda", name: "Corinda", wedge: false },
  { slug: "darra", name: "Darra", wedge: false },
  { slug: "deagon", name: "Deagon", wedge: false },
  { slug: "doolandella", name: "Doolandella", wedge: false },
  { slug: "drewvale", name: "Drewvale", wedge: false },
  { slug: "durack", name: "Durack", wedge: false },
  { slug: "eagle-farm", name: "Eagle Farm", wedge: false },
  { slug: "east-brisbane", name: "East Brisbane", wedge: false },
  { slug: "eight-mile-plains", name: "Eight Mile Plains", wedge: false },
  { slug: "ellen-grove", name: "Ellen Grove", wedge: false },
  { slug: "england-creek", name: "England Creek", wedge: false },
  { slug: "enoggera", name: "Enoggera", wedge: false },
  { slug: "enoggera-reservoir", name: "Enoggera Reservoir", wedge: false },
  { slug: "everton-park", name: "Everton Park", wedge: false },
  { slug: "ferny-grove", name: "Ferny Grove", wedge: false },
  { slug: "fig-tree-pocket", name: "Fig Tree Pocket", wedge: false },
  { slug: "fitzgibbon", name: "Fitzgibbon", wedge: false },
  { slug: "forest-lake", name: "Forest Lake", wedge: false },
  { slug: "fortitude-valley", name: "Fortitude Valley", wedge: false },
  { slug: "gaythorne", name: "Gaythorne", wedge: false },
  { slug: "geebung", name: "Geebung", wedge: false },
  { slug: "gordon-park", name: "Gordon Park", wedge: false },
  { slug: "graceville", name: "Graceville", wedge: false },
  { slug: "grange", name: "Grange", wedge: false },
  { slug: "gumdale", name: "Gumdale", wedge: false },
  { slug: "hamilton", name: "Hamilton", wedge: false },
  { slug: "hawthorne", name: "Hawthorne", wedge: false },
  { slug: "heathwood", name: "Heathwood", wedge: false },
  { slug: "hemmant", name: "Hemmant", wedge: false },
  { slug: "hendra", name: "Hendra", wedge: false },
  { slug: "herston", name: "Herston", wedge: false },
  { slug: "holland-park", name: "Holland Park", wedge: false },
  { slug: "holland-park-west", name: "Holland Park West", wedge: false },
  { slug: "inala", name: "Inala", wedge: false },
  { slug: "indooroopilly", name: "Indooroopilly", wedge: false },
  { slug: "jamboree-heights", name: "Jamboree Heights", wedge: false },
  { slug: "jindalee", name: "Jindalee", wedge: false },
  { slug: "kalinga", name: "Kalinga", wedge: false },
  { slug: "kangaroo-point", name: "Kangaroo Point", wedge: false },
  { slug: "karana-downs", name: "Karana Downs", wedge: false },
  { slug: "karawatha", name: "Karawatha", wedge: false },
  { slug: "kedron", name: "Kedron", wedge: false },
  { slug: "kelvin-grove", name: "Kelvin Grove", wedge: false },
  { slug: "kenmore", name: "Kenmore", wedge: false },
  { slug: "kenmore-hills", name: "Kenmore Hills", wedge: false },
  { slug: "keperra", name: "Keperra", wedge: false },
  { slug: "kholo", name: "Kholo", wedge: false },
  { slug: "kuraby", name: "Kuraby", wedge: false },
  { slug: "lake-manchester", name: "Lake Manchester", wedge: false },
  { slug: "larapinta", name: "Larapinta", wedge: false },
  { slug: "lota", name: "Lota", wedge: false },
  { slug: "lutwyche", name: "Lutwyche", wedge: false },
  { slug: "lytton", name: "Lytton", wedge: false },
  { slug: "macgregor", name: "Macgregor", wedge: false },
  { slug: "mackenzie", name: "Mackenzie", wedge: false },
  { slug: "manly", name: "Manly", wedge: false },
  { slug: "manly-west", name: "Manly West", wedge: false },
  { slug: "mansfield", name: "Mansfield", wedge: false },
  { slug: "mcdowall", name: "McDowall", wedge: false },
  { slug: "middle-park", name: "Middle Park", wedge: false },
  { slug: "milton", name: "Milton", wedge: false },
  { slug: "mitchelton", name: "Mitchelton", wedge: false },
  { slug: "moggill", name: "Moggill", wedge: false },
  { slug: "morningside", name: "Morningside", wedge: false },
  { slug: "mount-coot-tha", name: "Mount Coot-tha", wedge: false },
  { slug: "mount-crosby", name: "Mount Crosby", wedge: false },
  { slug: "mount-gravatt", name: "Mount Gravatt", wedge: false },
  { slug: "mount-gravatt-east", name: "Mount Gravatt East", wedge: false },
  { slug: "mount-ommaney", name: "Mount Ommaney", wedge: false },
  { slug: "murarrie", name: "Murarrie", wedge: false },
  { slug: "nathan", name: "Nathan", wedge: false },
  { slug: "new-farm", name: "New Farm", wedge: false },
  { slug: "newmarket", name: "Newmarket", wedge: false },
  { slug: "newstead", name: "Newstead", wedge: false },
  { slug: "norman-park", name: "Norman Park", wedge: false },
  { slug: "northgate", name: "Northgate", wedge: false },
  { slug: "nudgee", name: "Nudgee", wedge: false },
  { slug: "nudgee-beach", name: "Nudgee Beach", wedge: false },
  { slug: "nundah", name: "Nundah", wedge: false },
  { slug: "oxley", name: "Oxley", wedge: false },
  { slug: "paddington", name: "Paddington", wedge: false },
  { slug: "pallara", name: "Pallara", wedge: false },
  { slug: "parkinson", name: "Parkinson", wedge: false },
  { slug: "petrie-terrace", name: "Petrie Terrace", wedge: false },
  { slug: "pinjarra-hills", name: "Pinjarra Hills", wedge: false },
  { slug: "pinkenba", name: "Pinkenba", wedge: false },
  { slug: "port-of-brisbane", name: "Port Of Brisbane", wedge: false },
  { slug: "pullenvale", name: "Pullenvale", wedge: false },
  { slug: "ransome", name: "Ransome", wedge: false },
  { slug: "red-hill", name: "Red Hill", wedge: false },
  { slug: "richlands", name: "Richlands", wedge: false },
  { slug: "riverhills", name: "Riverhills", wedge: false },
  { slug: "robertson", name: "Robertson", wedge: false },
  { slug: "rochedale", name: "Rochedale", wedge: false },
  { slug: "runcorn", name: "Runcorn", wedge: false },
  { slug: "sandgate", name: "Sandgate", wedge: false },
  { slug: "seven-hills", name: "Seven Hills", wedge: false },
  { slug: "seventeen-mile-rocks", name: "Seventeen Mile Rocks", wedge: false },
  { slug: "sherwood", name: "Sherwood", wedge: false },
  { slug: "shorncliffe", name: "Shorncliffe", wedge: false },
  { slug: "sinnamon-park", name: "Sinnamon Park", wedge: false },
  { slug: "spring-hill", name: "Spring Hill", wedge: false },
  { slug: "st-lucia", name: "St Lucia", wedge: false },
  { slug: "stafford", name: "Stafford", wedge: false },
  { slug: "stafford-heights", name: "Stafford Heights", wedge: false },
  { slug: "stones-corner", name: "Stones Corner", wedge: false },
  { slug: "stretton", name: "Stretton", wedge: false },
  { slug: "sumner", name: "Sumner", wedge: false },
  { slug: "sunnybank", name: "Sunnybank", wedge: false },
  { slug: "sunnybank-hills", name: "Sunnybank Hills", wedge: false },
  { slug: "taigum", name: "Taigum", wedge: false },
  { slug: "taringa", name: "Taringa", wedge: false },
  { slug: "teneriffe", name: "Teneriffe", wedge: false },
  { slug: "the-gap", name: "The Gap", wedge: false },
  { slug: "tingalpa", name: "Tingalpa", wedge: false },
  { slug: "toowong", name: "Toowong", wedge: false },
  { slug: "upper-brookfield", name: "Upper Brookfield", wedge: false },
  { slug: "upper-kedron", name: "Upper Kedron", wedge: false },
  { slug: "upper-mount-gravatt", name: "Upper Mount Gravatt", wedge: false },
  { slug: "virginia", name: "Virginia", wedge: false },
  { slug: "wacol", name: "Wacol", wedge: false },
  { slug: "wakerley", name: "Wakerley", wedge: false },
  { slug: "wavell-heights", name: "Wavell Heights", wedge: false },
  { slug: "westlake", name: "Westlake", wedge: false },
  { slug: "willawong", name: "Willawong", wedge: false },
  { slug: "wilston", name: "Wilston", wedge: false },
  { slug: "windsor", name: "Windsor", wedge: false },
  { slug: "wishart", name: "Wishart", wedge: false },
  { slug: "wooloowin", name: "Wooloowin", wedge: false },
  { slug: "wynnum", name: "Wynnum", wedge: false },
  { slug: "wynnum-west", name: "Wynnum West", wedge: false },
  { slug: "zillmere", name: "Zillmere", wedge: false },
];

