// <auto-generated />
using System;
using GoodSort.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodSort.Api.Migrations
{
    [DbContext(typeof(GoodSortDbContext))]
    [Migration("20260415015822_AddVisionCalls")]
    partial class AddVisionCalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("EstimatedWeightKg")
                        .HasColumnType("float");

                    b.Property<string>("HostedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastCollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingContainers")
                        .HasColumnType("int");

                    b.Property<int>("PendingValueCents")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Lat", "Lng");

                    b.ToTable("Bins");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepotName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EarnedCents")
                        .HasColumnType("int");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StopCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.CollectionRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DriverPayoutCents")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedDurationMin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("int");

                    b.Property<int>("TotalValueCents")
                        .HasColumnType("int");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("DriverId");

                    b.HasIndex("Status");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "201 Montague Rd, West End",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = -27.478999999999999,
                            Lng = 153.00800000000001,
                            Name = "Tomra South Brisbane"
                        });
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedBags")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedWeightKg")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingContainers")
                        .HasColumnType("int");

                    b.Property<int>("PendingValueCents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Lat", "Lng");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.PricingConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AfternoonNormal")
                        .HasColumnType("float");

                    b.Property<int>("AluminiumSpotCents")
                        .HasColumnType("int");

                    b.Property<int>("BaseCents")
                        .HasColumnType("int");

                    b.Property<double>("BinDensityWeight")
                        .HasColumnType("float");

                    b.Property<int>("BronzeBonus")
                        .HasColumnType("int");

                    b.Property<int>("CeilingCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceEfficiencyWeight")
                        .HasColumnType("float");

                    b.Property<double>("EveningSurge")
                        .HasColumnType("float");

                    b.Property<int>("FloorCents")
                        .HasColumnType("int");

                    b.Property<int>("GlassSpotCents")
                        .HasColumnType("int");

                    b.Property<int>("GoldBonus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("MaterialMixWeight")
                        .HasColumnType("float");

                    b.Property<double>("MorningSurge")
                        .HasColumnType("float");

                    b.Property<double>("NightDiscount")
                        .HasColumnType("float");

                    b.Property<int>("PetSpotCents")
                        .HasColumnType("int");

                    b.Property<int>("PlatinumBonus")
                        .HasColumnType("int");

                    b.Property<double>("ScrapPriceWeight")
                        .HasColumnType("float");

                    b.Property<int>("SilverBonus")
                        .HasColumnType("int");

                    b.Property<double>("SupplyDemandWeight")
                        .HasColumnType("float");

                    b.Property<double>("TimeOfDayWeight")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("PricingConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AfternoonNormal = 1.0,
                            AluminiumSpotCents = 120,
                            BaseCents = 5,
                            BinDensityWeight = 0.20000000000000001,
                            BronzeBonus = 0,
                            CeilingCents = 8,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistanceEfficiencyWeight = 0.20000000000000001,
                            EveningSurge = 1.1000000000000001,
                            FloorCents = 3,
                            GlassSpotCents = 5,
                            GoldBonus = 1,
                            IsActive = true,
                            MaterialMixWeight = 0.10000000000000001,
                            MorningSurge = 1.3,
                            NightDiscount = 0.69999999999999996,
                            PetSpotCents = 30,
                            PlatinumBonus = 2,
                            ScrapPriceWeight = 0.14999999999999999,
                            SilverBonus = 0,
                            SupplyDemandWeight = 0.25,
                            TimeOfDayWeight = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Badges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClearedCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingCents")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCo2SavedKg")
                        .HasColumnType("float");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Phone")
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualContainerCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedBags")
                        .HasColumnType("int");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualContainers")
                        .HasColumnType("int");

                    b.Property<double>("ActualDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("ActualPayoutCents")
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CentroidLat")
                        .HasColumnType("float");

                    b.Property<double>("CentroidLng")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DropPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstimatedContainers")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedDurationMin")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedPayoutCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPricedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerContainerCents")
                        .HasColumnType("int");

                    b.Property<int>("PricingTier")
                        .HasColumnType("int");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DropPointId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RunnerId");

                    b.HasIndex("Status");

                    b.HasIndex("CentroidLat", "CentroidLng");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualContainers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedContainers")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("RunStops");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Badges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityBags")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("int");

                    b.Property<double>("EfficiencyScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<double?>("LastLat")
                        .HasColumnType("float");

                    b.Property<double?>("LastLng")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastLocationAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRunCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LifetimeEarningsCents")
                        .HasColumnType("int");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<double>("ServiceRadiusKm")
                        .HasColumnType("float");

                    b.Property<int>("TotalContainersCollected")
                        .HasColumnType("int");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsOnline");

                    b.HasIndex("Level");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("RunnerProfiles");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunnerRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BagCondition")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<double>("PickupCompleteness")
                        .HasColumnType("float");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<double>("Timeliness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("RunnerId");

                    b.ToTable("RunnerRatings");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("BinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefundCents")
                        .HasColumnType("int");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BinCode");

                    b.HasIndex("BinId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.VisionCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Provider");

                    b.ToTable("VisionCalls");
                });

            modelBuilder.Entity("GoodSort.Api.Services.CashoutRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AmountCents")
                        .HasColumnType("int");

                    b.Property<string>("Bsb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CashoutRequests");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Bin", b =>
                {
                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("BinId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("BinId");

                            b1.ToTable("Bins");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("BinId");
                        });

                    b.Navigation("Materials")
                        .IsRequired();
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Collection", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.CollectionRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.CollectionRoute", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Depot");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Household", b =>
                {
                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("HouseholdId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("HouseholdId");

                            b1.ToTable("Households");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdId");
                        });

                    b.Navigation("Materials")
                        .IsRequired();
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Profile", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RouteStop", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.CollectionRoute", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("RouteStopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("RouteStopId");

                            b1.ToTable("RouteStops");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("RouteStopId");
                        });

                    b.Navigation("Household");

                    b.Navigation("Materials");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Run", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Depot", "DropPoint")
                        .WithMany()
                        .HasForeignKey("DropPointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.RunnerProfile", "Runner")
                        .WithMany("Runs")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("RunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("RunId");

                            b1.ToTable("Runs");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("RunId");
                        });

                    b.Navigation("DropPoint");

                    b.Navigation("Materials")
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunStop", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.Run", "Run")
                        .WithMany("Stops")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("RunStopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("RunStopId");

                            b1.ToTable("RunStops");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("RunStopId");
                        });

                    b.Navigation("Bin");

                    b.Navigation("Materials");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunnerProfile", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("GoodSort.Api.Data.Entities.RunnerProfile", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunnerRating", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Run", "Run")
                        .WithOne("Rating")
                        .HasForeignKey("GoodSort.Api.Data.Entities.RunnerRating", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.RunnerProfile", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Scan", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "User")
                        .WithMany("Scans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodSort.Api.Services.CashoutRequest", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.CollectionRoute", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Household", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Profile", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Run", b =>
                {
                    b.Navigation("Rating");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RunnerProfile", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
