// <auto-generated />
using System;
using GoodSort.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodSort.Api.Migrations
{
    [DbContext(typeof(GoodSortDbContext))]
    partial class GoodSortDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepotName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EarnedCents")
                        .HasColumnType("int");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StopCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.CollectionRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DriverPayoutCents")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedDurationMin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("int");

                    b.Property<int>("TotalValueCents")
                        .HasColumnType("int");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("DriverId");

                    b.HasIndex("Status");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "201 Montague Rd, West End",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = -27.478999999999999,
                            Lng = 153.00800000000001,
                            Name = "Tomra South Brisbane"
                        });
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedBags")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedWeightKg")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingContainers")
                        .HasColumnType("int");

                    b.Property<int>("PendingValueCents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Lat", "Lng");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Badges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClearedCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingCents")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCo2SavedKg")
                        .HasColumnType("float");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualContainerCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedBags")
                        .HasColumnType("int");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefundCents")
                        .HasColumnType("int");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Collection", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.CollectionRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.CollectionRoute", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Depot");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Household", b =>
                {
                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("HouseholdId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("HouseholdId");

                            b1.ToTable("Households");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdId");
                        });

                    b.Navigation("Materials")
                        .IsRequired();
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Profile", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.RouteStop", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.CollectionRoute", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GoodSort.Api.Data.Entities.MaterialBreakdown", "Materials", b1 =>
                        {
                            b1.Property<Guid>("RouteStopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Aluminium")
                                .HasColumnType("int");

                            b1.Property<int>("Glass")
                                .HasColumnType("int");

                            b1.Property<int>("Other")
                                .HasColumnType("int");

                            b1.Property<int>("Pet")
                                .HasColumnType("int");

                            b1.HasKey("RouteStopId");

                            b1.ToTable("RouteStops");

                            b1.ToJson("Materials");

                            b1.WithOwner()
                                .HasForeignKey("RouteStopId");
                        });

                    b.Navigation("Household");

                    b.Navigation("Materials");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Scan", b =>
                {
                    b.HasOne("GoodSort.Api.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodSort.Api.Data.Entities.Profile", "User")
                        .WithMany("Scans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.CollectionRoute", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Household", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GoodSort.Api.Data.Entities.Profile", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
